"""
Generate SFT training data for Game-of-24 with Tree-of-Thought style traces.

For each puzzle, a brute-force solver enumerates all valid expressions that
equal 24, then a trace generator produces a structured response showing a few
failed attempts followed by the correct solution.

The output parquet has two columns:
  prompt   – plain question text (chat template applied by SFTDataset)
  response – full assistant response: reasoning trace + <answer> tag

Input : data/game24/train.parquet  (generated by prepare_data_game24.sh)
Output: data/sft_game24/train.parquet + val.parquet

Usage (from project root):
  conda run -n zero python3 examples/data_preprocess/generate_sft_game24.py
"""

import os
import random
import argparse
from fractions import Fraction
import pandas as pd
from datasets import Dataset


TARGET = 24
OPERATORS = ('+', '-', '*', '/')


# ──────────────────────────────── Solver ─────────────────────────────────── #

def _apply(a: Fraction, b: Fraction, op: str):
    if op == '+': return a + b
    if op == '-': return a - b
    if op == '*': return a * b
    if op == '/' and b != 0: return a / b
    return None


def _build_expr(ei: str, ej: str, op: str) -> str:
    """Combine two sub-expression strings with correct precedence parentheses."""
    low = set('+-')
    hi  = set('*/')
    if op in hi:
        if set(ei) & low: ei = f'({ei})'
        if set(ej) & low: ej = f'({ej})'
    if op == '-':
        if set(ej) & low: ej = f'({ej})'
    if op == '/':
        if set(ej) & (low | hi): ej = f'({ej})'
    return f'{ei} {op} {ej}'


def solve24(numbers):
    """Return a deduplicated list of expression strings that evaluate to 24."""

    def search(vals, exprs, acc):
        if len(vals) == 1:
            if vals[0] == TARGET:
                acc.append(exprs[0])
            return
        n = len(vals)
        for i in range(n):
            for j in range(n):
                if i == j:
                    continue
                rest_v = [vals[k] for k in range(n) if k not in (i, j)]
                rest_e = [exprs[k] for k in range(n) if k not in (i, j)]
                for op in OPERATORS:
                    r = _apply(vals[i], vals[j], op)
                    if r is None:
                        continue
                    search([r] + rest_v,
                           [_build_expr(exprs[i], exprs[j], op)] + rest_e,
                           acc)

    acc = []
    search([Fraction(n) for n in numbers], [str(n) for n in numbers], acc)
    seen, unique = set(), []
    for e in acc:
        if e not in seen:
            seen.add(e)
            unique.append(e)
    return unique


def _pick_solution(solutions: list) -> str:
    """Pick the most readable solution (fewest characters / parentheses)."""
    return min(solutions, key=lambda s: len(s) + s.count('(') * 2)


# ──────────────────────────── Trace generator ────────────────────────────── #

def _fmt(val) -> str:
    try:
        f = float(val)
        return str(int(f)) if f == int(f) else f'{f:.2f}'
    except Exception:
        return str(val)


def _generate_failures(numbers: list, n: int = 3) -> list:
    """
    Return n simple arithmetic attempts that demonstrably do not equal 24.
    Includes at least one fraction/division attempt so the model also sees the
    non-integer search direction (which the hard test puzzles often require).
    """
    a, b, c, d = sorted(numbers, reverse=True)

    def safe(fn):
        try:
            v = fn()
            return None if v is None else float(v)
        except Exception:
            return None

    # integer-style attempts first, then fraction/division attempts
    raw_candidates = [
        (f'{a} + {b} + {c} + {d}',            safe(lambda: a+b+c+d)),
        (f'{a} * {b} - {c} - {d}',            safe(lambda: a*b-c-d)),
        (f'({a} + {b}) * {c} - {d}',          safe(lambda: (a+b)*c-d)),
        (f'{a} * {b} + {c} - {d}',            safe(lambda: a*b+c-d)),
        (f'({a} - {b}) * ({c} + {d})',         safe(lambda: (a-b)*(c+d))),
        (f'{a} * {b} - {c} * {d}',            safe(lambda: a*b-c*d)),
    ]
    frac_candidates = [
        (f'{a} / ({b} / {c})',                safe(lambda: a/(b/c) if b and c else None)),
        (f'({a} + {b}) / ({c} / {d})',        safe(lambda: (a+b)/(c/d) if c and d else None)),
        (f'{a} * {b} / {c} + {d}',            safe(lambda: a*b/c+d if c else None)),
    ]

    def collect(cands, k):
        out = []
        for expr, result in cands:
            if result is None or abs(result - TARGET) < 1e-6:
                continue
            out.append(f'{expr} = {_fmt(result)} ≠ {TARGET}')
            if len(out) >= k:
                break
        return out

    # guarantee at least one fraction attempt when n>=3
    n_frac = 1 if n >= 3 else 0
    failures = collect(raw_candidates, n - n_frac) + collect(frac_candidates, n_frac)
    if len(failures) < n:  # backfill if a bucket was short
        failures += collect(raw_candidates + frac_candidates, n - len(failures))
    return failures[:n]


def generate_trace(numbers, sol: str = None):
    """
    Generate a ToT reasoning trace for a 24-point puzzle, optionally using a
    specific solution `sol`. Adds a self-check line so the model learns to
    verify its own answer. Returns the full assistant response, or None if
    unsolvable.
    """
    if sol is None:
        solutions = solve24(numbers)
        if not solutions:
            return None
        sol = _pick_solution(solutions)

    fails = _generate_failures(numbers, n=3)

    lines = [
        f'I need to make {TARGET} from {list(numbers)}, '
        f'using each number exactly once.\n'
    ]

    if fails:
        lines.append("Let me try some combinations first:")
        for f in fails:
            lines.append(f'- Try {f}. Does not work.')
        lines.append('\nLet me think differently:')
    else:
        lines.append('Let me analyze the combinations:')

    lines.append(f'{sol} = {TARGET} ✓  Found it!')
    lines.append(f'Check: {sol} = {TARGET}. Uses {list(numbers)} once each. Correct.')

    think = '\n'.join(lines)
    return (
        f'Let me solve this step by step.\n'
        f'<think>\n{think}\n</think>\n'
        f'<answer>{sol}</answer>'
    )


def pick_solutions(numbers, k: int = 2) -> list:
    """Pick up to k diverse valid solutions: the shortest, plus (if available)
    one that uses division (fraction pattern), else the next-shortest."""
    sols = solve24(numbers)
    if not sols:
        return []
    sols_sorted = sorted(sols, key=lambda s: len(s) + s.count('(') * 2)
    chosen = [sols_sorted[0]]
    if k >= 2:
        frac = next((s for s in sols_sorted[1:] if '/' in s), None)
        second = frac or (sols_sorted[1] if len(sols_sorted) > 1 else None)
        if second and second not in chosen:
            chosen.append(second)
    return chosen[:k]


def make_question(numbers: list) -> str:
    return (
        f'Using the numbers {list(numbers)}, create an equation that equals 24. '
        f'You can use basic arithmetic operations (+, -, *, /) and each number must be '
        f'used exactly once. Show your work in <think> </think> tags. Return the final '
        f'answer in <answer> </answer> tags, for example <answer> (1 + 2) * 8 </answer>.'
    )


# ─────────────────────────────────── Main ────────────────────────────────── #

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--input_parquet', default='data/game24/train.parquet')
    parser.add_argument('--output_dir',    default='data/sft_game24')
    parser.add_argument('--val_split',     type=float, default=0.05)
    parser.add_argument('--solutions_per_puzzle', type=int, default=2,
                        help='emit up to this many diverse solutions per puzzle (SFT v2 uses 2)')
    parser.add_argument('--seed',          type=int,   default=42)
    args = parser.parse_args()

    random.seed(args.seed)

    print(f'Loading {args.input_parquet} ...')
    df = pd.read_parquet(args.input_parquet)

    samples, skipped = [], 0
    for _, row in df.iterrows():
        gt      = row['reward_model']['ground_truth']
        numbers = list(gt['numbers'])

        sols = pick_solutions(numbers, k=args.solutions_per_puzzle)
        if not sols:
            skipped += 1
            continue
        for sol in sols:
            response = generate_trace(numbers, sol=sol)
            samples.append({'prompt': make_question(numbers), 'response': response})

    print(f'Generated {len(samples)} samples from {len(df)} puzzles, skipped {skipped} unsolvable.')

    random.shuffle(samples)
    n_val         = max(1, int(len(samples) * args.val_split))
    val_samples   = samples[:n_val]
    train_samples = samples[n_val:]

    os.makedirs(args.output_dir, exist_ok=True)
    Dataset.from_list(train_samples).to_parquet(
        os.path.join(args.output_dir, 'train.parquet'))
    Dataset.from_list(val_samples).to_parquet(
        os.path.join(args.output_dir, 'val.parquet'))

    print(f'Train: {len(train_samples)},  Val: {len(val_samples)}')
    print(f'Saved to {args.output_dir}/')

    # Show one example
    ex = samples[0]
    print('\n' + '=' * 60)
    print('PROMPT:\n', ex['prompt'])
    print('\nRESPONSE:\n', ex['response'])
    print('=' * 60)


if __name__ == '__main__':
    main()
